config/routes.rb
Rails.application.routes.draw do
  root 'notices#index'

  resources :notices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many :sessions

  validates :title, presence: true
  validates :openings, presence: true

  accepts_nested_attributes_for :sessions
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :notice

  validates :date, presence: true
  validates :time, presence: true
  validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  def index
    @notices = Notice.all
  end

  def show
  end

  def new
    @notice = Notice.new
    @notice.sessions.build 
  end

  def edit
  end

  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
        send_notice
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def send_notice
    $bot_runner.primary_channel.send_message('New notice incoming!')
  end

  def set_notice
    @notice = Notice.find(params[:id])
  end

  def notice_params
    params.require(:notice).permit(:title, :sessions, :openings, :author, :notes, :reward, :requester, 
                                   { sessions_attributes: [:date, :time, :location] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sacred Bell Noticeboard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .fixed
      = render '/navigation_bar'

      %main.container.my-3
        = yield

app/views/notices/_form.html.haml
.card
  = form_with(model: notice, local: true) do |form|
    - if notice.errors.any?
      #error_explanation
        %h2.alert.alert-danger
          = pluralize(notice.errors.count, "error")
          prohibited this notice from being saved:
        %ul
          - notice.errors.full_messages.each do |message|
            %li= message
    .field.form-group.m-3
      = form.label :title
      = form.text_field :title, class: 'form-control'
    .field.form-group.m-3
      = form.label :openings
      = form.number_field :openings, class: 'form-control'
    .field.form-group.m-3
      = form.label :author
      = form.text_field :author, class: 'form-control'
    .field.form-group.m-3
      = form.label :notes
      = form.text_area :notes, class: 'form-control'
    .field.form-group.m-3
      = form.label :reward
      = form.text_field :reward, class: 'form-control'
    .field.form-group.m-3
      = form.label :requester
      = form.text_field :requester, class: 'form-control'
    #sessions
      = form.fields_for :sessions do |session|
        = render 'session_fields', f: session
      = link_to_add_association 'Add another session', form, :sessions, class: 'btn float-right btn-primary btn-sm m-3'
    .actions.card-footer
      = form.submit 'Create Notice', class: 'btn btn-success btn-sm'

app/views/notices/_session_fields.html.haml
.nested-fields.m-3
  .card
    .card-body
      .float-right
        = link_to_remove_association "Remove session", f, class: 'btn btn-sm btn-danger'
      .field.form-group
        = f.label :date
        = f.date_select :date, class: 'form-control'
      .field.form-group
        = f.label :time
        = f.time_select :time, class: 'form-control'
      .field.form-group
        = f.label :location
        = f.text_field :location, class: 'form-control'

app/views/notices/edit.html.haml
%h1 Editing Notice
= render 'form', notice: @notice
= link_to 'Show', @notice
|
= link_to 'Back', notices_path

app/views/notices/index.html.haml
%p#notice= notice
%h1 Notices
%table.table
  %thead
    %tr
      %th Title
      %th Openings
      %th Author
      %th Reward
      %th Requester
      %th{:colspan => "3"}
  %tbody
    - @notices.each do |notice|
      %tr
        %td= notice.title
        %td= notice.openings
        %td= notice.notes
        %td= notice.reward
        %td= notice.requester
        %td= link_to 'Show', notice
        %td= link_to 'Edit', edit_notice_path(notice)
        %td= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Notice', new_notice_path

app/views/notices/new.html.haml
%h1 New Notice
= render 'form', notice: @notice

app/views/notices/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @notice.title
%p
  %strong Sessions:
  = @notice.sessions
%p
  %strong Openings:
  = @notice.openings
%p
  %strong Author:
  = @notice.author
%p
  %strong Notes:
  = @notice.notes
%p
  %strong Reward:
  = @notice.reward
%p
  %strong Requester:
  = @notice.requester
= link_to 'Edit', edit_notice_path(@notice)
|
= link_to 'Back', notices_path